
# Mastodon API

@baseUrl = {{$dotenv MastodonUrl}}
@accountId = {{$dotenv AccountId}}

### 固定投稿一覧取得
GET {{baseUrl}}/api/v1/accounts/{{accountId}}/statuses?pinned&limit=1 HTTP/1.1
Authorization: Bearer {{$dotenv MonitoringToken}}

### アカウント情報取得
GET {{baseUrl}}/api/v1/accounts/verify_credentials HTTP/1.1
Authorization: Bearer {{$dotenv MonitoringToken}}

### アカウント情報設定
PATCH {{baseUrl}}/api/v1/accounts/update_credentials HTTP/1.1
Authorization: Bearer {{$dotenv MonitoringToken}}
Content-Type: application/json

{
}