
# Mastodon API

@baseUrl = {{$dotenv MastodonUrl}}
@accountId = {{$dotenv AccountId}}

### 固定投稿一覧取得
GET {{baseUrl}}/api/v1/accounts/{{accountId}}/statuses?pinned&limit=1 HTTP/1.1
Authorization: Bearer {{$dotenv Token}}

### アカウント情報取得
GET {{baseUrl}}/api/v1/accounts/verify_credentials HTTP/1.1
Authorization: Bearer {{$dotenv Token}}

### アカウント情報設定
PATCH {{baseUrl}}/api/v1/accounts/update_credentials HTTP/1.1
Authorization: Bearer {{$dotenv Token}}
Content-Type: application/json

{
    "discoverable": true,
    "indexable": true
}

### アクセストークン取得
GET {{baseUrl}}/oauth/authorize?response_type=code&client_id={{$dotenv CLIENT_ID}}&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope={{$dotenv SCOPE}} HTTP/1.1

### アクセストークン取得
POST {{baseUrl}}/oauth/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv CLIENT_ID}}&client_secret={{$dotenv CLIENT_SECRET}}&grant_type=authorization_code&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope={{$dotenv SCOPE}}&code={{$dotenv CODE}}