name: Docker Build and Push

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-buildx-action@v3
    - uses: gittools/actions/gitversion/setup@v1
      with:
        versionSpec: '5.x'
    - uses: gittools/actions/gitversion/execute@v1
    - run: |
        IMAGE_ID=${{ github.repository }}
        IMAGE_ID=${IMAGE_ID,,}
        echo "image_tag=$IMAGE_ID" >> $GITHUB_ENV
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v6
      with:
        context: .
        build-args: |
          Repository=${{ github.repository }}
          Version=${{ env.GitVersion_FullSemVer }}
          AssemblyVersion=${{ env.GitVersion_AssemblySemVer }}
          FileVersion=${{ env.GitVersion_AssemblySemFileVer }}
          InformationalVersion=${{ env.GitVersion_InformationalVersion }}
        labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
        push: ${{ github.ref_name == 'master' }}
        tags: ghcr.io/${{ env.image_tag }}:${{ env.GitVersion_FullSemVer }},ghcr.io/${{ env.image_tag }}:dev
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - uses: getsentry/action-release@v1
      if: github.ref == 'refs/heads/master'
      env:
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      with:
        environment: production
        version: ${{ env.GitVersion_InformationalVersion }}
